variant: fcos
version: 1.6.0

passwd:
  users:
    - name: infini-ops
      groups: [sudo, docker]
      home_dir: /home/infini-ops
      shell: /bin/bash
      ssh_authorized_keys:
        # SSH public key for infini-ops user
        - ssh-ed25519 [YOUR_PUBLIC_KEY] infini-ops@infini-app

storage:
  files:
    # Script to assign random static IP on first boot
    - path: /usr/local/bin/set-random-ip.sh
      mode: 0755
      user:
        name: infini-ops
      contents:
        source: "https://raw.githubusercontent.com/YonKu0/infini-app/refs/heads/main/scripts/set-random-ip.sh"
        verification:
          hash: "sha256-4adc92c5a4714bf5b10c2cd78f8c3bc63e52e80151c216f8944b6a33795d164d"

    # Docker Compose CLI plugin with verification
    - path: /usr/local/bin/docker-compose
      mode: 0755
      user:
        name: infini-ops
      contents:
        source: "https://github.com/docker/compose/releases/download/v2.35.1/docker-compose-linux-x86_64"
        verification:
          hash: "sha256-7bdb2ce2916e5dd0354e5d129892bf96fdcdb1a9ab8eed69b9173e131db4c230"

    # Docker Buildx CLI plugin with verification
    - path: /usr/local/lib/docker/cli-plugins/docker-buildx
      mode: 0755
      user:
        name: infini-ops
      contents:
        source: "https://github.com/docker/buildx/releases/download/v0.23.0/buildx-v0.23.0.linux-amd64"
        verification:
          hash: "sha256-55838fdd095084e158e06a63635a07fe8a8bc6cb4db507f203394dc1ffa7fb8b"

systemd:
  units:
    # Assign random IP on first boot
    - name: set-random-ip.service
      enabled: true
      contents: |
        [Unit]
        Description=Set random static IP on first boot only
        ConditionFirstBoot=yes
        Wants=network-online.target NetworkManager-wait-online.service
        After=network-online.target NetworkManager-wait-online.service

        [Service]
        Type=oneshot
        ExecStart=/usr/local/bin/set-random-ip.sh
        RemainAfterExit=yes
        StandardOutput=journal
        StandardError=journal

        [Install]
        WantedBy=multi-user.target

    # Start the Docker daemon immediately at boot
    - name: docker.service
      enabled: true
