services:
  app:
    container_name: infini-app
    build: .
    restart: unless-stopped

    environment:
      HOST: 0.0.0.0
      PORT: 5050
      DEBUG: "false"
      DB_PATH: /data/app.db

    ports:
      - "5050:5050"

    volumes:
      - app_data:/data

    networks:
      - app_network

    # Logging retention
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    # Lock down the container filesystem
    read_only: true
    tmpfs:
      - /tmp

    # Drop all Linux capabilities and forbid privilege escalation
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
    ports:
      - "9090:9090"
    networks:
      - app_network
    depends_on:
      - app
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app_network:
    driver: bridge

volumes:
  app_data:
    driver: local
